### ISSUE TITLE
request help

### ISSUE THREAD

**Issue by rvnox** [devanshbatham/rayder#7]
![image](https://github.com/devanshbatham/rayder/assets/67718036/de0916b5-67d7-46f5-ab8f-4b1dac8f1892)
![image](https://github.com/devanshbatham/rayder/assets/67718036/cdeca913-3916-43de-a893-3e9c9dc07a3d)

I encounter an error when using the -it flag, but it works fine when I use either the -i or -t flag.
And the same happens when silent=true. Is it possible to support the -it flag ?

If I use the -i flag, I can exit a running Docker container with Ctrl+C. However, an error message is displayed
![image](https://github.com/devanshbatham/rayder/assets/67718036/5156e59f-45ad-4944-bac3-432732b3b068)

"If I only use the -t flag, I cannot exit a running container with Ctrl+C.
![image](https://github.com/devanshbatham/rayder/assets/67718036/382039d9-6cd4-42f2-adf1-276f156dbf2a)

thank you very much ！

**Comment by devanshbatham** [comment]
It is suggested to use a directly, without using docker, will add something to support docker commands.
